name: rechtum
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^0.21.0+1
  provider: ^5.0.0
  get_it: ^6.1.1
  openai_gpt3_api:
    git:
      url: https://github.com/LeonStaufer/openai_gpt3_dart_api
  bubble: ^1.2.1
  introduction_screen: ^2.1.0
  vrouter: ^1.1.0+20
  native_pdf_view: ^4.0.1

dev_dependencies:
  pedantic: ^1.11.0
  flutter_launcher_icons: ^0.9.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: IBM Plex Sans
      fonts:
        - asset: fonts/IBMPlexSans-Regular.ttf
        - asset: fonts/IBMPlexSans-Bold.ttf
          weight: 700
        - asset: fonts/IBMPlexSans-Light.ttf
          weight: 300
        - asset: fonts/IBMPlexSans-Italic.ttf
          style: italic
    - family: Open Sans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
        - asset: fonts/OpenSans-Light.ttf
          weight: 300

flutter_icons:
  image_path: "assets/icon.png"
  android: true
  ios: true

